version: '3.8'
services:
  web:
    build: .
    ports:
      - "4567:4567"
    environment:
      - RACK_ENV=development
      - GIFMACHINE_PASSWORD=foo
      - DATABASE_URL=postgres://postgres:postgres@db:5432/gifmachine
      - POSTGRES_PASSWORD=postgres
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17.2
    environment:
      - POSTGRES_DB=gifmachine
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
